### ISSUE TITLE
problem with use_scm_version 

### ISSUE THREAD

**Issue by teto** [gjcarneiro/pybindgen#15]
I am trying to update/fix several things in the nix ns3 and DCE packages so I wanted to fetch pybindgen from github (with the latest castxml patch) instead of pypi but the  scm version number seems to break ns3 identification:
```
Checking for python module 'pybindgen'                             : 0.0.post1+gef30ba2.d20180527 
Checking for pybindgen version                                     : 0.0.post1+gef30ba2.d20180527 
Traceback (most recent call last):
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 171, in run_commands
    ctx=run_command(cmd_name)
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 162, in run_command
    ctx.execute()
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Configure.py", line 87, in execute
    super(ConfigurationContext,self).execute()
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/teto/scratch/source/wscript", line 464, in configure
    conf.recurse('bindings/python')
  File "/home/teto/scratch/source/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/teto/scratch/source/bindings/python/wscript", line 198, in configure
    if not (split_version(pybindgen_version) >= split_version(REQUIRED_PYBINDGEN_VERSION)):
  File "/home/teto/scratch/source/bindings/python/wscript", line 75, in split_version
    return (int(ver[0]), int(ver[1]), int(ver[2]), int(ver[3].split('post')[1]))
ValueError: invalid literal for int() with base 10: 'post1'

```
I don't know this setting but I wonder if it could be configured in a way that better matches current version numbers  https://github.com/gjcarneiro/pybindgen/blob/ef30ba23dd23afe41aef5bc9aced71c112ccc22e/setup.py#L9 ?

Also it makes fetching the package from github harder since one can't use the github archive anymore.
 https://github.com/NixOS/nixpkgs/issues/41136#issuecomment-392329728 / https://github.com/kennethreitz/setup.py/issues/21

**Comment by gjcarneiro** [comment]
The current version  should be `0.18.0.post11+ngef30ba2`, not `0.0.post1+gef30ba2.d20180527`.  Is the version you get due to using a cloned git branch, where it doesn't find the tags?

Anyway, I think `0.18.0.post11+ngef30ba2` is fine as a local git version, but I'm happy to make a `0.19.0` release to pypi, if that helps?  Other than that, it's an ns-3 bug, not a pybindgen bug.

**Comment by teto** [comment]
having a pypi release would be the best. 
I think the system uses a shallow clone by default so that must be it.

**Comment by gjcarneiro** [comment]
uploaded 0.19.0.
